# Generated by Django 4.1.1 on 2022-10-01 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_category',
            new_name='type',
        ),
    ]
