# Generated by Django 3.2.15 on 2022-08-23 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilesingle',
            name='website_link',
        ),
        migrations.AddField(
            model_name='profilesingle',
            name='department_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profilesingle',
            name='github_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profilesingle',
            name='laboratory_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
