# Generated by Django 4.1.1 on 2022-10-01 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_project_category_project_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['category', '-date_of_addition']},
        ),
    ]
