# Generated by Django 3.2.15 on 2022-09-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220823_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilesingle',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='snippet',
            field=models.TextField(blank=True, null=True),
        ),
    ]
