# Generated by Django 4.1.1 on 2022-10-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['category', 'progress', '-date_of_addition']},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['author_rank', 'progress', '-publication_date']},
        ),
        migrations.AddField(
            model_name='project',
            name='progress',
            field=models.IntegerField(choices=[(0, 'In progress'), (1, 'Finished')], default=0),
        ),
        migrations.AddField(
            model_name='publication',
            name='progress',
            field=models.IntegerField(choices=[(0, 'In review'), (1, 'In press'), (2, 'Published')], default=0),
        ),
    ]
