# Generated by Django 2.0 on 2022-09-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20220907_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilesingle',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profilesingle',
            name='linkedin_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profilesingle',
            name='orcid_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profilesingle',
            name='researchgate_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
