# Generated by Django 4.1.1 on 2022-10-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_project_options_alter_publication_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='progress',
            field=models.IntegerField(choices=[('In progress', 'In progress'), ('Finished', 'Finished')], default=0),
        ),
    ]
