# Generated by Django 4.1.1 on 2022-10-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_project_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='progress',
            field=models.CharField(choices=[('In progress', 'In progress'), ('Finished', 'Finished')], default=0, max_length=255),
        ),
    ]
