# Generated by Django 4.1.1 on 2022-10-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_project_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='progress',
            field=models.CharField(choices=[('In review', 'In review'), ('In press', 'In press'), ('Published', 'Published')], default=0, max_length=255),
        ),
    ]
