# Generated by Django 2.2.5 on 2022-08-18 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_profilesingle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilesingle',
            old_name='user',
            new_name='user_name',
        ),
    ]
