# Generated by Django 2.2.5 on 2022-08-18 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20220819_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilesingle',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profilesingle',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
