# Generated by Django 2.2.5 on 2022-08-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20220819_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Draft'), (1, 'Publish')], default=1, null=True),
        ),
    ]
