# Generated by Django 2.2.5 on 2022-08-19 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='snippet',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
