# Generated by Django 2.2.5 on 2022-08-20 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20220819_2316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='date',
            new_name='publication_date',
        ),
    ]
