# Generated by Django 2.2.5 on 2022-08-20 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20220820_1337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-publication_date']},
        ),
    ]
