# Generated by Django 2.2.5 on 2022-08-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20220820_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
