# Generated by Django 3.2.15 on 2022-08-22 21:41

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_alter_publication_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='null'),
            preserve_default=False,
        ),
    ]
