# Generated by Django 3.2.15 on 2022-08-22 22:38

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_alter_publication_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
