# Generated by Django 3.2.15 on 2022-08-23 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_alter_publication_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
