# Generated by Django 3.2.15 on 2022-08-23 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20220823_2249'),
        ('blog', '0037_auto_20220823_1947'),
    ]

    operations = [
    ]
